export const EmailDomains = [
  "@student.annauniv.edu",
  "@annauniv.edu",
  "@auist.net",
];

export const AdminTypes = ["SuperAdmin", "Admin", "Analytics"];

export const UserAdditionType = ["Single", "Multiple"];

export const UserRemovalType = ["Single", "Multiple"];

export const LogoutUserType = ["Admin", "User"];

export const ResumeDownloadType = ["Personal", "College"];

export const AdminPanelOtpRequestReasons = [
  "Add Admin",
  "Remove Admin",
  "Modify Admin",
];

export const UserProfileOtpRequestReasons = [
  "Password Reset",
  "Get Logs",
  "Encryption Key Reset",
];

export const Departments = [
  "Information Science and Technology",
  "Biomedical Engineering",
  "Civil Engineering",
  "Computer Science and Engineering",
  "Chemistry",
  "Electrical and Electronics Engineering",
  "Electronics and Communication Engineering",
  "English",
  "Geology",
  "Industrial Engineering",
  "Mathematics",
  "Manufacturing Engineering",
  "Management Studies",
  "Mechanical Engineering",
  "Media Sciences",
  "Medical Physics",
  "Mining Engineering",
  "Physics",
  "Printing and Packaging Technology",
];

export const CourseTypes = ["Under Graduate", "Post Graduate"];

export const Programmes = [
  "B.E./B.Tech.",
  "B.Arch.",
  "M.C.A.",
  "M.E.",
  "M.Tech.",
  "M.Arch.",
  "M.Plan.",
  "M.Sc. (Five Years Integrated)",
  "M.Sc.",
  "M.B.A.",
];

export const Branches = [
  "Aeronautical Engineering",
  "Agriculture & Irrigation Engineering",
  "Apparel Technology",
  "Automobile Engineering",
  "Bio-Medical Engineering",
  "Ceramic Technology",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Science and Engineering",
  "Electrical and Electronics",
  "Electronics and Communication",
  "Electronics and Instrumentation",
  "Food Technology",
  "Geo Informatics",
  "Industrial Bio-Technology",
  "Industrial Engineering",
  "Information Technology",
  "Leather Technology",
  "Manufacturing Engineering",
  "Material Science and Engineering",
  "Mechanical Engineering",
  "Mining Engineering",
  "Pharmaceutical Technology",
  "Production Engineering",
  "Petroleum Engineering & Technology",
  "Rubber & Plastics Technology",
  "Textile Technology",
  "Printing & Packaging Technology",
  "Artificial Science & Data Science",
  "Robotics and Automation",
  "Architecture",
  "N/A",
  "Hydrology and Water Ress. Engineering",
  "Soil Mechs and Foundn. Engineering",
  "Structural Engineering",
  "Construction Engineering and Management",
  "Remote Sensing and Geomatics",
  "Transportation Engineering",
  "Environmental Engineering",
  "Irrigation Water Management",
  "Environmental Management",
  "Internal Combustion Engineering",
  "Thermal Engineering",
  "Energy Engineering",
  "Computer Integrated Manufacturing",
  "Industrial Engineering",
  "Manufacturing Systems and Mgmt.",
  "Solar Energy",
  "Quality Engineering and Mgmt.",
  "Aeronautical Engineering",
  "Avionics",
  "Aerospace",
  "Automobile Engineering",
  "Manufacturing Engineering",
  "Mechatronics",
  "Applied Electronics",
  "Biomedical Engineering",
  "Medical Electronics",
  "Communication Systems",
  "V.L.S.I Design",
  "Communication and Networking",
  "Wireless Technology",
  "VLSI and Embedded Systems",
  "Computer Science and Engineering",
  "Big Data Analytics",
  "Software Engineering",
  "Operation Research",
  "Multi Media Technology",
  "Information Technology",
  "Design Engineering",
  "Mobility Engineering",
  "Product Design and Development",
  "Printing and Packaging Technology",
  "Instrumentation Engg. Spcl in Industrial Automation",
  "High Voltage Engineering",
  "Power Systems Engineering",
  "Power Electronics and Drives",
  "Power Engineering and Management",
  "Control and Instrumentation Engineering",
  "Embedded Systems and Technologies",
  "Environmental Science and Tech.",
  "Laser & Electro-Optical Engg.",
  "Polymer Science and Engg.",
  "Chemical Engineering",
  "Ceramic Technology",
  "Petroleum Refining and Petro-Chemical",
  "Bio-Technology",
  "Bio-Pharmaceutical Technology",
  "Food Technology",
  "Textile Technology",
  "Leather Technology",
  "Footwear Science and Engineering",
  "Nano Science and Technology",
  "Industrial Safety and Hazard Management",
  "Rubber Technology",
  "Computational Biology",
  "Information Technology",
  "Information Technology spcl in AI and Data Science",
  "Ocean Technology",
  "Landscape Architecture",
  "Digital Architecture",
  "General",
  "Town and Country Planning",
  "Computer Science",
  "Information Technology",
  "Electronic Media",
  "Mathematics",
  "Material Science",
  "Medical Physics",
  "Applied Chemistry",
  "Applied Geology",
  "Environmental Science",
  "Electronics Media",
  "Multimedia",
  "Multimedia spcl in Viscom",
  "General Management",
  "Tourism Management",
];
